### ISSUE TITLE
Format of the Object version values

### ISSUE THREAD

**Issue by akeranen** [one-data-model/language#8] opened 2019-07-02 14:34 UTC
The object version [format](https://github.com/one-data-model/language/blob/master/sdf.md#information-block) is still TBD. We seem to be using somewhat consistently format `YYYYMMDD` (e.g., `20190424`).

**Comment by mjkoster** [comment] 2019-08-02 14:55
Duplicate of #31?

**Comment by asoloway64** [comment] 2019-10-01 12:12
F2F4: Agreed as duplicate.

**Closed** 2019-10-01 12:13 UTC
Labels: WDL, duplicate
